version: '3.4'

networks:
  gatewaynetwork:
    driver: bridge

volumes:
  gatewaydb_data:
    driver: local

services:
  globalintegrationdb:
      container_name: global-integration-db
      image: mcr.microsoft.com/mssql/server:2019-latest
      stdin_open: true
      ports:
          - "1533:1433"
      environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=password@12345#
      restart: always
      networks:
          - gatewaynetwork
      healthcheck:
        test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password@12345# -Q 'SELECT 1' || exit 1" ]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
      volumes:
         - ./globalintegrationdb_data:/docker-entrypoint-initdb.d
  globalintegrationdb.configurator:
      image: mcr.microsoft.com/mssql-tools:latest
      container_name: global-integration-db-configurator
      user: root
      volumes:
         - ./globalintegrationdb_data:/docker-entrypoint-initdb.d
      depends_on:
         globalintegrationdb:
           condition: service_healthy
      command: bash -c '/opt/mssql-tools/bin/sqlcmd -S global-integration-db -U sa -P password@12345# -i /docker-entrypoint-initdb.d/init.sql; echo "------------------------------ALLLL GLOOOOOBAAAAAAL!!!!---------------------------------";'
      networks:
         - gatewaynetwork
  gateway-global-integration-api:
    image: ${DOCKER_REGISTRY-}gatewayglobalintegrationapi
    build:
      context: .
      dockerfile: gateway-global-integration-api/Dockerfile
    depends_on:
         - gatewayrabbitmq
         - globalintegrationdb
    environment:
         #- SQL_DB_CONNECTION_STRING=
         #- APPLICATIONINSIGHTS_CONNECTION_STRING=
         #- AZURE_SERVICE_BUS_CONNECTION_STRING=
         #- CLIENT_BASE_URL= 
         - MSG_HOST=gateway-rabbitmq
    networks:
         - gatewaynetwork
  gatewayrabbitmq:
      image: rabbitmq:3.13.1-management
      container_name: gateway-rabbitmq
      ports:
        - "15672:15672"
        - "5672:5672"
      networks:
        - gatewaynetwork
